### ISSUE TITLE
Additional layout - Checklist (on hold)

### ISSUE THREAD

**Issue by banuragaxioned** [axioned/codex#3]
- [ ] Rename the original page layout as `snippet` (as these can be code or text or a combination of usual Markdown features)
- [ ] Create another page layout called `checklist` (these would typically be `ul` > `li` items - each having a title and description text)
- [ ] Swap out the main content area content with something that resembles a checklist
- [ ] These should be accessible through the following routes in the Next.js application `/snippet` and `/checklist`
